"""Draw the application icon and write the Windows version resource.

Keeps a binary .ico out of source control: run this once before building and it produces
build_assets/aerolab.ico plus version_info.txt for PyInstaller.
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))

from aerolab import __version__


def make_icon() -> Path:
    from PySide6.QtCore import QPoint, Qt
    from PySide6.QtGui import QColor, QGuiApplication, QIcon, QPainter, QPen, QPixmap

    app = QGuiApplication.instance() or QGuiApplication([])
    icon = QIcon()
    pixmaps = []
    for size in (16, 24, 32, 48, 64, 128, 256):
        pixmap = QPixmap(size, size)
        pixmap.fill(Qt.transparent)
        painter = QPainter(pixmap)
        painter.setRenderHint(QPainter.Antialiasing)
        s = size / 64.0
        painter.setBrush(QColor("#0072B2"))
        painter.setPen(Qt.NoPen)
        painter.drawRoundedRect(int(2 * s), int(2 * s), int(60 * s), int(60 * s),
                                14 * s, 14 * s)
        painter.setPen(QPen(QColor("#FFFFFF"), max(1.5, 5 * s), Qt.SolidLine,
                            Qt.RoundCap, Qt.RoundJoin))
        painter.drawPolyline([QPoint(int(14 * s), int(46 * s)), QPoint(int(26 * s), int(34 * s)),
                              QPoint(int(38 * s), int(38 * s)), QPoint(int(50 * s), int(18 * s))])
        painter.end()
        pixmaps.append(pixmap)
        icon.addPixmap(pixmap)

    path = HERE / "aerolab.ico"
    # Qt cannot write .ico, so pack the frames by hand — the format is simple enough.
    _write_ico(pixmaps, path)
    return path


def _write_ico(pixmaps, path: Path) -> None:
    """Write a multi-resolution .ico whose frames are PNG-encoded (Vista and later)."""
    import struct
    from PySide6.QtCore import QBuffer, QByteArray

    frames = []
    for pixmap in pixmaps:
        # The QByteArray must outlive the QBuffer: passing a temporary straight into the
        # constructor lets Python collect it mid-write, which segfaults.
        store = QByteArray()
        buffer = QBuffer(store)
        buffer.open(QBuffer.WriteOnly)
        pixmap.save(buffer, "PNG")
        buffer.close()
        frames.append((pixmap.width(), pixmap.height(), bytes(store)))

    header = struct.pack("<HHH", 0, 1, len(frames))
    offset = len(header) + 16 * len(frames)
    entries, payload = b"", b""
    for width, height, blob in frames:
        entries += struct.pack("<BBBBHHII", width % 256, height % 256, 0, 0, 1, 32,
                               len(blob), offset)
        payload += blob
        offset += len(blob)
    path.write_bytes(header + entries + payload)


def make_version_info() -> Path:
    parts = (__version__.split(".") + ["0", "0", "0"])[:4]
    numbers = ", ".join(str(int(p) if p.isdigit() else 0) for p in parts)
    text = f"""# Windows version resource, generated by make_icon.py
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({numbers}), prodvers=({numbers}),
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)
  ),
  kids=[
    StringFileInfo([StringTable('040904B0', [
        StringStruct('CompanyName', 'AeroLab Studio'),
        StringStruct('FileDescription', 'AeroLab Studio - aerogel fibre analysis'),
        StringStruct('FileVersion', '{__version__}'),
        StringStruct('InternalName', 'AeroLabStudio'),
        StringStruct('OriginalFilename', 'AeroLabStudio.exe'),
        StringStruct('ProductName', 'AeroLab Studio'),
        StringStruct('ProductVersion', '{__version__}')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    path = HERE / "version_info.txt"
    path.write_text(text, encoding="utf-8")
    return path


if __name__ == "__main__":
    icon = make_icon()
    version = make_version_info()
    print(f"icon    -> {icon}  ({icon.stat().st_size / 1024:.1f} kB)")
    print(f"version -> {version}")
